[project]
name = "perfed"
authors = [
  {name = "Enze Soh", email = "enzesoh@gmail.com"},
]
version = "0.1.0"
description = "Simplified performance timers in Python."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tabulate>=0.9.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pytest>=8.4.0",
]
